import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Modal from "./components/Modal";
import { Suspense } from "react";
import Link from "next/link";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Link href="?modal=true">
            <button type="button" className="bg-blue-500 text-white p-2">Open Modal</button>
        </Link>
        {children}
        <Modal/>
        </body>
        </html>
    )
}
