import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="nav-bar">
          <h3>
            <Link href="/">Home</Link>
          </h3>
          <h3>
            <Link href="/about">About</Link>
          </h3>
          <h3>
            <Link href="/contact">Contact</Link>
          </h3>
          <h3>
            <Link href="/not-existing-route">Not Found</Link>
          </h3>
          <h3>
            <Link href="/user">User</Link>
          </h3>
        </div>
        {children}
      </body>
    </html>
  );
}
